baseurl = "https://yui.syui.ai"
languageCode = "ja-jp"
title = "yui"
copyright = "&copy; syui"
paginate = 10000

[permalinks]
    blog = "/blog/post/:year/:month/:day/:slug"
    novel = "/novel/:slug"

[author]
	name = "syui"
[params]
    date_format = "2006-01-02"
    mainSections = ["post"]

[markup.goldmark.renderer]
  unsafe = true

[frontmatter]
	date  = [":filename", ":default"]

[taxonomies]
	tag = "tags"

[outputs]
  home = ["JSON", "HTML"]

#pygmentsCodeFences = false
